# Generated by Django 5.1.2 on 2024-12-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_alter_deletedfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_path',
        ),
    ]
