# Generated by Django 5.1.2 on 2024-12-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_remove_file_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_path',
            field=models.FileField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
