# Generated by Django 5.1.2 on 2024-12-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_file_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
