# Generated by Django 5.1.2 on 2024-12-29 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(
                null=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
