# Generated by Django 5.1.2 on 2024-12-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_file_folder_alter_folder_parent_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='parent_folder',
        ),
        migrations.AddField(
            model_name='folder',
            name='path',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
