# Generated by Django 5.1.2 on 2024-12-31 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_alter_folder_parent_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='parent_folder',
            new_name='parent',
        ),
    ]
