# Generated by Django 5.1.2 on 2024-12-31 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_rename_parent_folder_folder_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='parent',
            new_name='parent_folder',
        ),
    ]
