# Generated by Django 5.1.2 on 2024-12-31 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_folder_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='user',
            new_name='user_id',
        ),
    ]
