# Generated by Django 5.1.2 on 2024-12-31 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_rename_user_folder_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='myapp.folder'),
            preserve_default=False,
        ),
    ]
