# Generated by Django 5.1.2 on 2025-01-01 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0064_remove_folder_user_folder_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='user_id',
            new_name='user',
        ),
    ]
